name: Build wheel

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest, macos-latest-large]
    env:
      CIBW_SKIP: 'pp*'
      CIBW_ARCHS: 'auto64'
      CIBW_PROJECT_REQUIRES_PYTHON: '>=3.9'
    defaults:
      run:
        shell: bash -l {0}
     
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4      
        with:
          submodules: true
      - name: Set up Python version ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install OMP (MacOS) 
        if: runner.os == 'macOS'
        run: |
          brew install llvm libomp
          echo "export CC=/usr/local/opt/llvm/bin/clang" >> ~/.bashrc
          echo "export CFLAGS=\"$CFLAGS -I/usr/local/opt/libomp/include\"" >> ~/.bashrc
          echo "export CXXFLAGS=\"$CXXFLAGS -I/usr/local/opt/libomp/include\"" >> ~/.bashrc
          echo "export LDFLAGS=\"$LDFLAGS -Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp\"" >> ~/.bashrc
          source ~/.bashrc
      - name: Install OMP (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install libomp-dev
      - name: Build Wheel
        run: |
          python -m pip install cibuildwheel==2.16.5
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform }}
          path: ./wheelhouse/*.whl
      - name: Test Wheel
        run: |
          python -m pip install numpy
          python -m pip install --no-index --find-links wheelhouse/ rat
