name: Build and upload to PyPI

on:
  release:
    types:
        - published
  workflow_dispatch:

jobs:
  build_wheels:
    uses: StephenNneji/demo_recv/.github/workflows/build_wheel.yml@main

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        run: |
          pip install pybind11
          python setup.py sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - run: ls -R artifacts
