name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:

    strategy:
      matrix:
        os: [macos-latest]
        version: ["3.9"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4      

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install 
        run: |
          brew install llvm libomp
          export CC=/usr/local/opt/llvm/bin/clang
          export CFLAGS="$CFLAGS -I/usr/local/opt/libomp/include"
          export CXXFLAGS="$CXXFLAGS -I/usr/local/opt/libomp/include"
          export LDFLAGS="$LDFLAGS -Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"
          python -m pip install -e .
          cd rat
          ls
          cd ..
          python examples/DSPC_custom_layers_example.py
